table.insert(pfUI.gui.dropdowns.fonts, "Interface\\AddOns\\pfUI-font-roboto\\fonts\\Roboto-Black.ttf:Roboto (Black)")
table.insert(pfUI.gui.dropdowns.fonts, "Interface\\AddOns\\pfUI-font-roboto\\fonts\\Roboto-Bold.ttf:Roboto (Bold)")
table.insert(pfUI.gui.dropdowns.fonts, "Interface\\AddOns\\pfUI-font-roboto\\fonts\\Roboto-Light.ttf:Roboto (Light)")
table.insert(pfUI.gui.dropdowns.fonts, "Interface\\AddOns\\pfUI-font-roboto\\fonts\\Roboto-Medium.ttf:Roboto (Medium)")
table.insert(pfUI.gui.dropdowns.fonts, "Interface\\AddOns\\pfUI-font-roboto\\fonts\\Roboto-Regular.ttf:Roboto (Regular)")
table.insert(pfUI.gui.dropdowns.fonts, "Interface\\AddOns\\pfUI-font-roboto\\fonts\\Roboto-Thin.ttf:Roboto (Thin)")
